# For *SECRET* and *PEPPER* keys, use `rake secret` to generate secure keys.

SECRET_TOKEN: "<SECRET_TOKEN>"
COOKIE_STORE_KEY: "<COOKIE_STORE_KEY>"

DEVISE_PEPPER: "<DEVISE_PEPPER>"

DRAGONFLY_SECRET: "<DRAGONFLY_SECRET>"

MAILER_SENDER: "<MAILER_SENDER>"

# Set timezone to a specified zone. Run `rake -D time` for a list of tasks for finding time zone names.
# TIMEZONE: "UTC"

development:
  MONGODB_URI: "mongodb://<USER>:<PASSWORD>@<SERVER>:<PORT>/<DATABASE>"

test:
  MONGODB_URI: "mongodb://<USER>:<PASSWORD>@<SERVER>:<PORT>/<DATABASE>"

production:
  MONGODB_URI: "mongodb://<USER>:<PASSWORD>@<SERVER>:<PORT>/<DATABASE>"

  # If assets are hosted on Amazon S3:
  # S3_KEY_ID: "<S3_KEY_ID>"
  # S3_SECRET_KEY: "<S3_SECRET_KEY>"
  # S3_BUCKET_REGION: "<S3_BUCKET_REGION>"