SECRET_TOKEN: "SECRET_TOKEN"
COOKIE_STORE_KEY: "COOKIE_STORE_KEY"

DRAGONFLY_SECRET: "DRAGONFLY_SECRET"

development:
  MONGODB_URI: mongodb://user:password@server:port_name/database"

test:
  MONGODB_URI: mongodb://user:password@server:port_name/database"

production:
  MONGODB_URI: mongodb://user:password@server:port_name/database"

  # If assets are hosted on Amazon S3:
  # S3_KEY_ID: 'S3_KEY_ID'
  # S3_SECRET_KEY: 'S3_SECRET_KEY'
  # S3_BUCKET_REGION: 'S3_BUCKET_REGION'